// Generated by tools/build-geography.mjs from research/geography/*.jsonl.
// Edit the JSONL ledgers, then rerun the generator.

export const geographyPlaces = [
  {
    "id": "place.puerto-rico",
    "label": "Puerto Rico",
    "kind": "island",
    "geoid": "72",
    "coordinates": [
      -66.4107992,
      18.217648
    ],
    "precision": "state_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb Current States",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/0",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.caguas",
    "label": "Caguas",
    "kind": "municipio",
    "parent_ref": "place.puerto-rico",
    "geoid": "72025",
    "coordinates": [
      -66.0509643,
      18.2111085
    ],
    "precision": "municipio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb ACS 2025",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/11",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.cidra",
    "label": "Cidra",
    "kind": "municipio",
    "parent_ref": "place.puerto-rico",
    "geoid": "72041",
    "coordinates": [
      -66.1616287,
      18.1743011
    ],
    "precision": "municipio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb ACS 2025",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/11",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.fajardo",
    "label": "Fajardo",
    "kind": "municipio",
    "parent_ref": "place.puerto-rico",
    "geoid": "72053",
    "coordinates": [
      -65.588454,
      18.3863776
    ],
    "precision": "municipio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb ACS 2025",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/11",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.gurabo",
    "label": "Gurabo",
    "kind": "municipio",
    "parent_ref": "place.puerto-rico",
    "geoid": "72063",
    "coordinates": [
      -65.9809422,
      18.2718899
    ],
    "precision": "municipio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb ACS 2025",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/11",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.humacao",
    "label": "Humacao",
    "kind": "municipio",
    "parent_ref": "place.puerto-rico",
    "geoid": "72069",
    "coordinates": [
      -65.7862286,
      18.1354025
    ],
    "precision": "municipio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb ACS 2025",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/11",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.juncos",
    "label": "Juncos",
    "kind": "municipio",
    "parent_ref": "place.puerto-rico",
    "geoid": "72077",
    "coordinates": [
      -65.9085417,
      18.2241334
    ],
    "precision": "municipio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb ACS 2025",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/11",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.naguabo",
    "label": "Naguabo",
    "kind": "municipio",
    "parent_ref": "place.puerto-rico",
    "geoid": "72103",
    "coordinates": [
      -65.735749,
      18.2110697
    ],
    "precision": "municipio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb ACS 2025",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/11",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.san-lorenzo",
    "label": "San Lorenzo",
    "kind": "municipio",
    "parent_ref": "place.puerto-rico",
    "geoid": "72129",
    "coordinates": [
      -65.9769147,
      18.1469213
    ],
    "precision": "municipio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb ACS 2025",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/11",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.yabucoa",
    "label": "Yabucoa",
    "kind": "municipio",
    "parent_ref": "place.puerto-rico",
    "geoid": "72151",
    "coordinates": [
      -65.8598696,
      18.059859
    ],
    "precision": "municipio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb ACS 2025",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/11",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.anton-ruiz-humacao",
    "label": "Antón Ruíz, Humacao",
    "kind": "barrio",
    "parent_ref": "place.humacao",
    "geoid": "7206903239",
    "coordinates": [
      -65.7863151,
      18.1793997
    ],
    "precision": "barrio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb BAS 2026",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer/1",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.collores-humacao",
    "label": "Collores, Humacao",
    "kind": "barrio",
    "parent_ref": "place.humacao",
    "geoid": "7206919106",
    "coordinates": [
      -65.82024,
      18.1747025
    ],
    "precision": "barrio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb BAS 2026",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer/1",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.humacao-pueblo",
    "label": "Humacao barrio-pueblo",
    "kind": "barrio",
    "parent_ref": "place.humacao",
    "geoid": "7206935575",
    "coordinates": [
      -65.8249773,
      18.1514682
    ],
    "precision": "barrio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb BAS 2026",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer/1",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.mambiche-humacao",
    "label": "Mambiche, Humacao",
    "kind": "barrio",
    "parent_ref": "place.humacao",
    "geoid": "7206949507",
    "coordinates": [
      -65.810097,
      18.1973954
    ],
    "precision": "barrio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb BAS 2026",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer/1",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.hucares-naguabo",
    "label": "Húcares, Naguabo",
    "kind": "barrio",
    "parent_ref": "place.naguabo",
    "geoid": "7210335489",
    "coordinates": [
      -65.7177284,
      18.1968702
    ],
    "precision": "barrio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb BAS 2026",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer/1",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.rio-blanco-naguabo",
    "label": "Río Blanco, Naguabo",
    "kind": "barrio",
    "parent_ref": "place.naguabo",
    "geoid": "7210370491",
    "coordinates": [
      -65.7904232,
      18.2507419
    ],
    "precision": "barrio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb BAS 2026",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer/1",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.rincon-gurabo",
    "label": "Rincón, Gurabo",
    "kind": "barrio",
    "parent_ref": "place.gurabo",
    "geoid": "7206369545",
    "coordinates": [
      -65.9899932,
      18.2493488
    ],
    "precision": "barrio_internal_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb BAS 2026",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer/1",
      "accessed": "2026-07-24"
    }
  },
  {
    "id": "place.las-piedras",
    "label": "Las Piedras",
    "kind": "municipio",
    "parent_ref": "place.puerto-rico",
    "geoid": "72085",
    "coordinates": [
      -65.8693153,
      18.1875309
    ],
    "precision": "municipio_polygon_centroid_point",
    "coordinate_source": {
      "dataset": "U.S. Census Bureau TIGERweb ACS 2025",
      "url": "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/11",
      "accessed": "2026-07-24",
      "method": "Centroid calculated from the returned municipio polygon; representative area point, not a church or household coordinate."
    }
  }
] as const;

export const geographyEvents = [
  {
    "id": "geo.event.miguel-vazquez-baptism-1786",
    "date": "1786-10-18",
    "event_type": "baptism",
    "person_refs": [
      "person.miguel-vazquez-child-of-francisco-maria",
      "person.francisco-father-of-maximo-vazquez",
      "person.maria-cortez"
    ],
    "place_ref": "place.caguas",
    "status": "confirmed_original_parish_register",
    "evidence_refs": [
      "source.familysearch-baptism.miguel-vazquez.1786"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 1,
    "map_label": "Caguas · 1786",
    "map_note": "Miguel was baptized at a reported age of fifteen days, the legitimate son of Francisco Vázquez and María Magdalena."
  },
  {
    "id": "geo.event.simona-baptism-1790",
    "date": "1790-03-07",
    "event_type": "baptism",
    "person_refs": [
      "person.simona-ribera",
      "person.luis-father-of-josefa-rivera",
      "person.isidora-rodriguez"
    ],
    "place_ref": "place.las-piedras",
    "status": "confirmed",
    "evidence_refs": [
      "source.familysearch-baptism.simona-rivera.1790"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 2,
    "map_label": "Las Piedras · 1790",
    "map_note": "Simona, sister of Josefa, was baptized here to Luís de Rivera and Isidora Rodríguez."
  },
  {
    "id": "geo.event.ysabel-baptism-1792",
    "date": "1792-10-22",
    "event_type": "baptism",
    "person_refs": [
      "person.ysabel-daughter-of-luis-rivera",
      "person.luis-father-of-josefa-rivera",
      "person.isidora-rodriguez"
    ],
    "place_ref": "place.las-piedras",
    "status": "confirmed",
    "evidence_refs": [
      "source.familysearch-baptism.ysabel-rivera.1792"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 3,
    "map_label": "Las Piedras · 1792",
    "map_note": "Another daughter, Ysabel, was baptized in the same parish."
  },
  {
    "id": "geo.event.maria-de-los-angeles-burial-1793",
    "date": "1793-07-25",
    "event_type": "burial",
    "person_refs": [
      "person.maria-de-los-angeles-vazquez",
      "person.francisco-father-of-maximo-vazquez",
      "person.maria-cortez"
    ],
    "place_ref": "place.caguas",
    "status": "confirmed_original_parish_register",
    "evidence_refs": [
      "source.familysearch-burial.maria-de-los-angeles-vazquez.1793"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 4,
    "map_label": "Caguas · 1793",
    "map_note": "The child María de los Ángeles was buried as the legitimate daughter of Francisco Vázquez and María Magdalena."
  },
  {
    "id": "geo.event.maria-magdalena-cortes-burial-1794",
    "date": "1794-06-17",
    "event_type": "burial",
    "person_refs": [
      "person.maria-cortez",
      "person.francisco-father-of-maximo-vazquez"
    ],
    "place_ref": "place.caguas",
    "status": "confirmed_original_parish_register",
    "evidence_refs": [
      "source.familysearch-burial.maria-magdalena-cortes.1794"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 5,
    "map_label": "Caguas · 1794",
    "map_note": "María Magdalena Cortés was buried here as the legitimate wife of Francisco Vázquez."
  },
  {
    "id": "geo.event.jose-vazquez-burial-1801",
    "date": "1801-02-14",
    "event_type": "burial",
    "person_refs": [
      "person.jose-vazquez-child-of-francisco-maria",
      "person.francisco-father-of-maximo-vazquez",
      "person.maria-cortez"
    ],
    "place_ref": "place.caguas",
    "status": "confirmed_original_parish_register",
    "evidence_refs": [
      "source.familysearch-burial.jose-vazquez.1801"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 6,
    "map_label": "Caguas · 1801",
    "map_note": "José Vázquez was buried as the legitimate son of Francisco and María Cortés."
  },
  {
    "id": "geo.event.maximo-native-caguas",
    "date_range": "before 1819",
    "event_type": "reported_native_place",
    "person_refs": [
      "person.maximo-vazquez"
    ],
    "place_ref": "place.caguas",
    "status": "confirmed_as_recorded",
    "evidence_refs": [
      "source.familysearch-baptism.juan-de-dios-vazquez-rivera.1819"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 7,
    "map_label": "Caguas",
    "map_note": "Máximo was recorded as a native of Caguas in his son’s 1819 baptism."
  },
  {
    "id": "geo.event.josefa-native-humacao",
    "date_range": "before 1819",
    "event_type": "reported_native_place",
    "person_refs": [
      "person.josefa-rivera"
    ],
    "place_ref": "place.humacao",
    "status": "confirmed_as_recorded",
    "evidence_refs": [
      "source.familysearch-baptism.juan-de-dios-vazquez-rivera.1819"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 8,
    "map_label": "Humacao",
    "map_note": "The same baptism calls Josefa a native of Humacao."
  },
  {
    "id": "geo.event.luis-native-humacao",
    "date_range": "before 1811",
    "event_type": "reported_native_place",
    "person_refs": [
      "person.luis-father-of-josefa-rivera"
    ],
    "place_ref": "place.humacao",
    "status": "confirmed_as_recorded",
    "evidence_refs": [
      "source.familysearch-death.luis-de-rivera.1811"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 9,
    "map_label": "Humacao",
    "map_note": "Luís de Rivera's 1811 death calls him a native of this Humacao district."
  },
  {
    "id": "geo.event.maximo-josefa-marriage-1805",
    "date": "1805-12-31",
    "event_type": "marriage",
    "person_refs": [
      "person.maximo-vazquez",
      "person.josefa-rivera"
    ],
    "place_ref": "place.humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.familysearch-marriage.maximo-josefa.1805"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 10,
    "map_label": "Humacao · 1805",
    "map_note": "Máximo Basquez and Josefa Ribera married in Humacao."
  },
  {
    "id": "geo.event.juana-jacinta-birth-1806",
    "date": "1806-08-16",
    "event_type": "child_birth",
    "person_refs": [
      "person.maximo-vazquez",
      "person.josefa-rivera",
      "person.juana-jacinta-vazquez-rivera"
    ],
    "place_ref": "place.humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.familysearch-baptism.juana-jacinta-vazquez-rivera.1806"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 11,
    "map_label": "Humacao · 1806",
    "map_note": "Their daughter Juana Jacinta was born in Humacao."
  },
  {
    "id": "geo.event.luis-death-1811",
    "date": "1811",
    "event_type": "death",
    "person_refs": [
      "person.luis-father-of-josefa-rivera"
    ],
    "place_ref": "place.humacao",
    "status": "confirmed_year_exact_day_open",
    "evidence_refs": [
      "source.familysearch-death.luis-de-rivera.1811"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 12,
    "map_label": "Humacao · 1811",
    "map_note": "Luís died in Humacao. The entry names his parents, wife, and nine children."
  },
  {
    "id": "geo.event.family-juncos-1819",
    "date": "1819-03-14",
    "event_type": "child_baptism",
    "person_refs": [
      "person.maximo-vazquez",
      "person.josefa-rivera"
    ],
    "place_ref": "place.juncos",
    "status": "confirmed",
    "evidence_refs": [
      "source.familysearch-baptism.juan-de-dios-vazquez-rivera.1819"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 13,
    "map_label": "Juncos · 1819",
    "map_note": "Their son Juan de Dios was baptized in Juncos."
  },
  {
    "id": "geo.event.family-san-lorenzo-1824",
    "date": "1824-07-15",
    "event_type": "child_baptism",
    "person_refs": [
      "person.maximo-vazquez",
      "person.josefa-rivera"
    ],
    "place_ref": "place.san-lorenzo",
    "status": "confirmed",
    "evidence_refs": [
      "source.familysearch-baptism.miguel-de-los-santos.1824"
    ],
    "map_groups": [
      "early-vazquez"
    ],
    "sequence": 14,
    "map_label": "San Lorenzo · 1824",
    "map_note": "Their son Miguel de los Santos was baptized in San Lorenzo."
  },
  {
    "id": "geo.event.atilano-native-juncos",
    "date_range": "about 1828",
    "event_type": "reported_birth_place",
    "person_refs": [
      "person.atilano-vazquez"
    ],
    "place_ref": "place.juncos",
    "status": "approximate_date_place_confirmed_as_recorded",
    "evidence_refs": [
      "source.familysearch-marriage.atilano-juana.1849",
      "source.familysearch-death.atilano.1898"
    ],
    "map_groups": [
      "atilano-juana"
    ],
    "sequence": 1,
    "map_label": "Juncos · c. 1828",
    "map_note": "Atilano was recorded as a native of Juncos; the year comes from his reported age at death."
  },
  {
    "id": "geo.event.atilano-juana-marriage-1849",
    "date": "1849-02-10",
    "event_type": "marriage",
    "person_refs": [
      "person.atilano-vazquez",
      "person.juana-rodriguez"
    ],
    "place_ref": "place.yabucoa",
    "status": "confirmed",
    "evidence_refs": [
      "source.familysearch-marriage.atilano-juana.1849"
    ],
    "map_groups": [
      "atilano-juana"
    ],
    "sequence": 2,
    "map_label": "Yabucoa · 1849",
    "map_note": "Atilano and Juana Regina married and raised their family in Yabucoa."
  },
  {
    "id": "geo.event.atilano-death-1898",
    "date": "1898-06-03",
    "event_type": "death",
    "person_refs": [
      "person.atilano-vazquez"
    ],
    "place_ref": "place.yabucoa",
    "status": "confirmed",
    "evidence_refs": [
      "source.familysearch-death.atilano.1898",
      "source.familysearch-civil-death.atilano.1898"
    ],
    "map_groups": [
      "atilano-juana"
    ],
    "sequence": 3,
    "map_label": "Yabucoa · 1898",
    "map_note": "Parish and civil records agree that Atilano died in Yabucoa."
  },
  {
    "id": "geo.event.sotero-marriage-1875",
    "date_range": "1875-09-16 to 1875-09-25",
    "event_type": "marriage",
    "person_refs": [
      "person.sotero-vazquez",
      "person.maria-eugenia-rodriguez"
    ],
    "place_ref": "place.yabucoa",
    "status": "confirmed_date_bracketed",
    "evidence_refs": [
      "source.familysearch-marriage.sotero-maria-eugenia.1875"
    ],
    "map_groups": [
      "sotero-maria"
    ],
    "sequence": 1,
    "map_label": "Yabucoa · 1875",
    "map_note": "Their undated marriage entry falls between records dated 16 and 25 September."
  },
  {
    "id": "geo.event.sotero-household-1910",
    "date": "1910-04-25",
    "event_type": "residence",
    "person_refs": [
      "person.sotero-vazquez",
      "person.maria-eugenia-rodriguez"
    ],
    "place_ref": "place.anton-ruiz-humacao",
    "status": "confirmed_household_identity",
    "evidence_refs": [
      "source.census.1910.sotero-maria"
    ],
    "map_groups": [
      "sotero-maria"
    ],
    "sequence": 2,
    "map_label": "Antón Ruíz · 1910",
    "map_note": "The census places Sotero, María, Braulio, and Francisco in Antón Ruíz."
  },
  {
    "id": "geo.event.sotero-death-1916",
    "date": "1916-05-31",
    "event_type": "death",
    "person_refs": [
      "person.sotero-vazquez"
    ],
    "place_ref": "place.humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.familysearch-death.sotero-vazquez.1916"
    ],
    "map_groups": [
      "sotero-maria"
    ],
    "sequence": 3,
    "map_label": "Humacao · 1916",
    "map_note": "Sotero died in Humacao; the act names seven living children."
  },
  {
    "id": "geo.event.maria-death-1933",
    "date": "1933-07-06",
    "event_type": "death",
    "person_refs": [
      "person.maria-eugenia-rodriguez"
    ],
    "place_ref": "place.anton-ruiz-humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.pr-civil-death.maria-eugenia.685901"
    ],
    "map_groups": [
      "sotero-maria"
    ],
    "sequence": 4,
    "map_label": "Antón Ruíz · 1933",
    "map_note": "María Eugenia died in Antón Ruíz as Sotero’s widow."
  },
  {
    "id": "geo.event.juan-birth-1878",
    "date": "1878-08-30",
    "event_type": "birth",
    "person_refs": [
      "person.juan-vazquez-rodriguez"
    ],
    "place_ref": "place.yabucoa",
    "status": "confirmed",
    "evidence_refs": [
      "source.familysearch-baptism.juan-de-la-rosa-vazquez.1878"
    ],
    "map_groups": [
      "juan-carlina"
    ],
    "sequence": 1,
    "map_label": "Yabucoa · 1878",
    "map_note": "Juan de la Rosa was born in Yabucoa and baptized there six weeks later."
  },
  {
    "id": "geo.event.carlina-native-naguabo",
    "date_range": "about 1881–1882",
    "event_type": "reported_birth_place",
    "person_refs": [
      "person.carlina-perales-perez"
    ],
    "place_ref": "place.naguabo",
    "status": "strong_date_approximate",
    "evidence_refs": [
      "source.pr-civil-marriage.juan-carlina.1530270",
      "source.pr-civil-death.carlina.681091"
    ],
    "map_groups": [
      "juan-carlina"
    ],
    "sequence": 2,
    "map_label": "Naguabo · c. 1881",
    "map_note": "Carlina’s marriage and death records place her birth in Naguabo."
  },
  {
    "id": "geo.event.juan-carlina-marriage-1902",
    "date": "1902-09-25",
    "event_type": "marriage",
    "person_refs": [
      "person.juan-vazquez-rodriguez",
      "person.carlina-perales-perez"
    ],
    "place_ref": "place.humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.pr-civil-marriage.juan-carlina.1530270"
    ],
    "map_groups": [
      "juan-carlina"
    ],
    "sequence": 3,
    "map_label": "Humacao · 1902",
    "map_note": "Juan and Carlina married in Humacao."
  },
  {
    "id": "geo.event.rafael-birth-1906",
    "date_range": "February 1906",
    "event_type": "birth",
    "person_refs": [
      "person.rafael-vazquez-perales"
    ],
    "place_ref": "place.humacao",
    "status": "confirmed_month_exact_day_open",
    "evidence_refs": [
      "source.pr-civil-birth.rafael.649515"
    ],
    "map_groups": [
      "rafael"
    ],
    "sequence": 1,
    "map_label": "Humacao · 1906",
    "map_note": "Rafael’s civil registration supports February 1906; the exact day is unresolved."
  },
  {
    "id": "geo.event.rafael-anton-ruiz-1910",
    "date": "1910-04",
    "event_type": "residence",
    "person_refs": [
      "person.rafael-vazquez-perales",
      "person.juan-vazquez-rodriguez",
      "person.carlina-perales-perez"
    ],
    "place_ref": "place.anton-ruiz-humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.census.1910.rafael"
    ],
    "map_groups": [
      "rafael",
      "juan-carlina"
    ],
    "sequence": 4,
    "map_label": "Antón Ruíz · 1910",
    "map_note": "Rafael was a child in Juan and Carlina’s household."
  },
  {
    "id": "geo.event.rafael-anton-ruiz-1920",
    "date": "1920-01",
    "event_type": "residence",
    "person_refs": [
      "person.rafael-vazquez-perales",
      "person.juan-vazquez-rodriguez",
      "person.carlina-perales-perez"
    ],
    "place_ref": "place.anton-ruiz-humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.census.1920.rafael"
    ],
    "map_groups": [
      "rafael",
      "juan-carlina"
    ],
    "sequence": 5,
    "map_label": "Antón Ruíz · 1920",
    "map_note": "A second census finds Rafael in the same family household."
  },
  {
    "id": "geo.event.rafael-mambiche-1930",
    "date": "1930-04",
    "event_type": "residence",
    "person_refs": [
      "person.rafael-vazquez-perales",
      "person.juan-vazquez-rodriguez"
    ],
    "place_ref": "place.mambiche-humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.census.1930.rafael"
    ],
    "map_groups": [
      "rafael",
      "juan-carlina"
    ],
    "sequence": 6,
    "map_label": "Mambiche · 1930",
    "map_note": "Rafael, now an adult, was still in Juan’s household."
  },
  {
    "id": "geo.event.marcelino-native-naguabo",
    "date_range": "about 1841",
    "event_type": "reported_birth_place",
    "person_refs": [
      "person.marcelino-perales-medina"
    ],
    "place_ref": "place.naguabo",
    "status": "confirmed_place_date_approximate",
    "evidence_refs": [
      "source.pr-civil-death.marcelino-perales.4607227"
    ],
    "map_groups": [
      "marcelino-aurora"
    ],
    "sequence": 1,
    "map_label": "Naguabo · c. 1841",
    "map_note": "Marcelino’s death act records him as born and resident in Naguabo."
  },
  {
    "id": "geo.event.marcelino-death-1891",
    "date": "1891-05-13",
    "event_type": "death",
    "person_refs": [
      "person.marcelino-perales-medina"
    ],
    "place_ref": "place.naguabo",
    "status": "confirmed",
    "evidence_refs": [
      "source.pr-civil-death.marcelino-perales.4607227"
    ],
    "map_groups": [
      "marcelino-aurora"
    ],
    "sequence": 2,
    "map_label": "Naguabo · 1891",
    "map_note": "Marcelino died in Naguabo, leaving Aurora a widow."
  },
  {
    "id": "geo.event.aurora-rio-blanco-1935",
    "date": "1935",
    "event_type": "residence",
    "person_refs": [
      "person.aurora-perez"
    ],
    "place_ref": "place.rio-blanco-naguabo",
    "status": "confirmed",
    "evidence_refs": [
      "source.census.1935.aurora-hilaria"
    ],
    "map_groups": [
      "marcelino-aurora"
    ],
    "sequence": 3,
    "map_label": "Río Blanco · 1935",
    "map_note": "Aurora lived with daughter Hilaria in Río Blanco."
  },
  {
    "id": "geo.event.aurora-rio-blanco-1940",
    "date": "1940-04-05",
    "event_type": "residence",
    "person_refs": [
      "person.aurora-perez"
    ],
    "place_ref": "place.rio-blanco-naguabo",
    "status": "confirmed",
    "evidence_refs": [
      "source.census.1940.aurora-hilaria"
    ],
    "map_groups": [
      "marcelino-aurora"
    ],
    "sequence": 4,
    "map_label": "Río Blanco · 1940",
    "map_note": "The 1940 census finds Aurora in the same household."
  },
  {
    "id": "geo.event.mauricio-carmen-marriage-1907",
    "date": "1907-10-23",
    "event_type": "marriage",
    "person_refs": [
      "person.mauricio-reyes",
      "person.carmen-diaz"
    ],
    "place_ref": "place.fajardo",
    "status": "confirmed",
    "evidence_refs": [
      "source.pr-civil-marriage.mauricio-carmen.4865948"
    ],
    "map_groups": [
      "mauricio-carmen"
    ],
    "sequence": 1,
    "map_label": "Fajardo · 1907",
    "map_note": "Mauricio and Carmen married in Fajardo."
  },
  {
    "id": "geo.event.reyes-hucares-1910",
    "date": "1910-04",
    "event_type": "residence",
    "person_refs": [
      "person.mauricio-reyes",
      "person.carmen-diaz"
    ],
    "place_ref": "place.hucares-naguabo",
    "status": "confirmed",
    "evidence_refs": [
      "source.census.1910.reyes-diaz"
    ],
    "map_groups": [
      "mauricio-carmen"
    ],
    "sequence": 2,
    "map_label": "Húcares · 1910",
    "map_note": "The couple and daughter Juana lived in Carmen’s parents’ Naguabo household."
  },
  {
    "id": "geo.event.cruz-birth-1915",
    "date": "1915-05-03",
    "event_type": "birth",
    "person_refs": [
      "person.cruz-reyes-vasquez",
      "person.mauricio-reyes",
      "person.carmen-diaz"
    ],
    "place_ref": "place.rincon-gurabo",
    "status": "confirmed",
    "evidence_refs": [
      "source.pr-civil-birth.cruz.3790159"
    ],
    "map_groups": [
      "cruz",
      "mauricio-carmen"
    ],
    "sequence": 3,
    "map_label": "Rincón · 1915",
    "map_note": "Cruz was born in barrio Rincón, Gurabo."
  },
  {
    "id": "geo.event.reyes-anton-ruiz-1920",
    "date": "1920-01",
    "event_type": "residence",
    "person_refs": [
      "person.cruz-reyes-vasquez",
      "person.mauricio-reyes",
      "person.carmen-diaz"
    ],
    "place_ref": "place.anton-ruiz-humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.census.1920.reyes-diaz"
    ],
    "map_groups": [
      "cruz",
      "mauricio-carmen"
    ],
    "sequence": 4,
    "map_label": "Antón Ruíz · 1920",
    "map_note": "The Reyes–Díaz household included Cruz and her brothers and sisters."
  },
  {
    "id": "geo.event.reyes-mambiche-1930",
    "date": "1930-04",
    "event_type": "residence",
    "person_refs": [
      "person.cruz-reyes-vasquez",
      "person.mauricio-reyes",
      "person.carmen-diaz"
    ],
    "place_ref": "place.mambiche-humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.census.1930.reyes-diaz"
    ],
    "map_groups": [
      "cruz",
      "mauricio-carmen"
    ],
    "sequence": 5,
    "map_label": "Mambiche · 1930",
    "map_note": "The family moved within Humacao to Mambiche."
  },
  {
    "id": "geo.event.reyes-collores-1935",
    "date": "1935",
    "event_type": "residence",
    "person_refs": [
      "person.cruz-reyes-vasquez",
      "person.mauricio-reyes",
      "person.carmen-diaz"
    ],
    "place_ref": "place.collores-humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.census.1935.reyes-diaz"
    ],
    "map_groups": [
      "cruz",
      "mauricio-carmen"
    ],
    "sequence": 6,
    "map_label": "Collores · 1935",
    "map_note": "The Puerto Rico social census places the household in Collores."
  },
  {
    "id": "geo.event.reyes-collores-1940",
    "date": "1940-04-04",
    "event_type": "residence",
    "person_refs": [
      "person.cruz-reyes-vasquez",
      "person.mauricio-reyes",
      "person.carmen-diaz"
    ],
    "place_ref": "place.collores-humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.census.1940.reyes-diaz"
    ],
    "map_groups": [
      "cruz",
      "mauricio-carmen"
    ],
    "sequence": 7,
    "map_label": "Collores · 1940",
    "map_note": "Cruz was still in her parents’ household eighteen months before her Manhattan marriage."
  },
  {
    "id": "geo.event.pedro-ana-anton-ruiz-1910",
    "date_range": "1910-04-20 to 1910-04-21",
    "event_type": "residence",
    "person_refs": [
      "person.pedro-reyes",
      "person.ana-martinez"
    ],
    "place_ref": "place.anton-ruiz-humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.census.1910.pedro-ana-julian"
    ],
    "map_groups": [
      "pedro-ana"
    ],
    "sequence": 1,
    "map_label": "Antón Ruíz · 1910",
    "map_note": "Their household crosses two census sheets and includes son Julián."
  },
  {
    "id": "geo.event.pedro-death-1918",
    "date": "1918-01-03",
    "event_type": "death",
    "person_refs": [
      "person.pedro-reyes"
    ],
    "place_ref": "place.humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.pr-civil-death.pedro-reyes.678330"
    ],
    "map_groups": [
      "pedro-ana"
    ],
    "sequence": 2,
    "map_label": "Humacao · Jan. 1918",
    "map_note": "Pedro died in Humacao."
  },
  {
    "id": "geo.event.ana-death-1918",
    "date": "1918-03-21",
    "event_type": "death",
    "person_refs": [
      "person.ana-martinez"
    ],
    "place_ref": "place.humacao",
    "status": "confirmed",
    "evidence_refs": [
      "source.pr-civil-death.ana-martinez.45678048"
    ],
    "map_groups": [
      "pedro-ana"
    ],
    "sequence": 3,
    "map_label": "Humacao · Mar. 1918",
    "map_note": "Ana died there less than three months later."
  },
  {
    "id": "geo.event.juan-dolores-mambiche-1930",
    "date": "1930-04-11",
    "event_type": "residence",
    "person_refs": [
      "person.juan-vazquez-rodriguez",
      "person.dolores-rivera"
    ],
    "place_ref": "place.mambiche-humacao",
    "status": "confirmed_consensual_household",
    "evidence_refs": [
      "source.familysearch-census.1930.juan-dolores"
    ],
    "map_groups": [
      "juan-carlina"
    ],
    "sequence": 7,
    "map_label": "Mambiche · 1930",
    "map_note": "Juan and Dolores Rivera headed a household containing children from Juan's earlier marriage and their Vázquez Rivera children."
  },
  {
    "id": "geo.event.juan-dolores-anton-ruiz-1940",
    "date": "1940-04-25",
    "event_type": "residence",
    "person_refs": [
      "person.juan-vazquez-rodriguez",
      "person.dolores-rivera"
    ],
    "place_ref": "place.anton-ruiz-humacao",
    "status": "confirmed_consensual_household",
    "evidence_refs": [
      "source.familysearch-census.1940.juan-dolores"
    ],
    "map_groups": [
      "juan-carlina"
    ],
    "sequence": 8,
    "map_label": "Antón Ruíz · 1940",
    "map_note": "The census again recorded Juan and Dolores together, both marked CC, contrato consensual."
  }
] as const;
