export const sources = [
  {
    id: "cruz-birth",
    label: "1915 civil registration: Cruz Reyes Díaz",
    detail: "Born 3 May 1915 in barrio Rincón, Gurabo. Maternal grandfather Lope Díaz registered the birth on 17 June; the act gives the name Cruz and names both parents and both sets of grandparents.",
    href: "https://www.ancestry.com/search/collections/9100/records/3790159",
    grade: "Original civil record",
  },
  {
    id: "reyes-marriage-1907",
    label: "1907 marriage: Mauricio Reyes Martínez and Carmen Díaz García",
    detail: "Married 23 October 1907 in Fajardo; parents Pedro Reyes and Ana Martínez, and Lope Díaz and Reyes García.",
    href: "https://www.ancestry.com/search/collections/9100/records/4865948",
    grade: "Original civil record",
  },
  {
    id: "mauricio-baptism-1882",
    label: "1882 baptism: Mauricio Reyes Martínez",
    detail: "Baptized 23 February 1882 in Humacao; parents Pedro Reyes and Ana Martínez; grandparents Ramón Reyes and Inés Castro, and Dámaso Martínez and María Rivera. The entry’s birth-year wording is impossible and remains unresolved.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSF3-6SVL-5?view=fullText&keywords=Pedro+Reyes%2CReyes%2CPedro%2CAna+Mart%C3%ADnez%2CHumacao&lang=en",
    grade: "Original parish register · birth-year conflict retained",
  },
  {
    id: "pedro-ana-census-1910",
    label: "1910 census: Pedro Reyes, Ana Martínez, and Julián Reyes",
    detail: "Anton Ruiz, Humacao. The household crosses sheets 5B–6A. Pedro’s marriage to Ana was his second and her first; Ana reported seven children born and four living.",
    href: "https://www.familysearch.org/ark:/61903/1:1:VWKH-5D5?lang=en",
    grade: "Original enumeration · two adjacent pages",
  },
  {
    id: "benito-isabel-baptism-1877",
    label: "1877 baptism: Benito Isabel Reyes Martínez",
    detail: "Born 8 July and baptized 15 September 1877 in Humacao, a son of Pedro Reyes and Ana Martínez. He is not merged with the later Isabel without a record connecting the names.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSFS-29WY-6?view=fullText&keywords=Reyes%2CAna+Mart%C3%ADnez%2CPedro+Reyes%2CHumacao&lang=en",
    grade: "Original parish register · identity question open",
  },
  {
    id: "anastacia-reyes-villafane-death",
    label: "1958 death: Anastacia Reyes Villafañe",
    detail: "Humacao death record naming Pedro Reyes and Juana Villafañe as her parents, confirming one of Mauricio’s paternal half-siblings.",
    href: "https://www.familysearch.org/ark:/61903/1:1:QVJS-K72H?lang=en",
    grade: "Original civil record",
  },
  {
    id: "pedro-reyes-villafane-death",
    label: "1897 death: Pedro Reyes Villafañe",
    detail: "Humacao death record naming Pedro Reyes and Juana Villafañe as his parents, confirming another of Mauricio’s paternal half-siblings.",
    href: "https://www.familysearch.org/ark:/61903/1:1:ZC2J-5DPZ?lang=en",
    grade: "Original civil record",
  },
  {
    id: "marriage",
    label: "1941 Manhattan marriage license",
    detail: "Rafael Vazquez and Cruz Reyes, married 25 October 1941; certificate 18978; all four parents named.",
    href: "https://www.ancestry.com/search/collections/61788/records/322345",
    grade: "Official-record index",
  },
  {
    id: "census-1910-reyes",
    label: "1910 Puerto Rico census: Reyes–Díaz household",
    detail: "Ucares, Naguabo; Mauricio and Carmen with daughter Juana in the home of Lope Díaz and Reyes García.",
    href: "https://www.ancestry.com/search/collections/7884/records/31899346",
    grade: "Original enumeration",
  },
  {
    id: "census-1920-reyes",
    label: "1920 Puerto Rico census: Reyes–Díaz household",
    detail: "Anton Ruiz, Humacao; Mauricio, Carmen, Cruz, Belén and their brothers and sisters.",
    href: "https://www.ancestry.com/search/collections/6061/records/59358916",
    grade: "Original enumeration",
  },
  {
    id: "census-1930-reyes",
    label: "1930 Puerto Rico census: Reyes–Díaz household",
    detail: "Mambiche, Humacao; the household includes Cruz, Belén, more siblings, Carmen’s brother Paulino, and her mother Reyes.",
    href: "https://www.ancestry.com/search/collections/6224/records/114623030",
    grade: "Original enumeration",
  },
  {
    id: "census-1935-reyes",
    label: "1935 Puerto Rico social census: Reyes–Díaz household",
    detail: "Collores, Humacao; Mauricio and Carmen with Eriberta, Cruz, Belén, Cándido, Saturnino, and Julio César.",
    href: "https://www.ancestry.com/search/collections/2404/records/390774",
    grade: "Original enumeration",
  },
  {
    id: "census-1940-reyes",
    label: "1940 Puerto Rico census: Reyes–Díaz household",
    detail: "Collores, Humacao, 4 April 1940; Mauricio and Carmen with Eriberta, Cruz, Aurora, Cándido, and Julio. The public image is cropped before younger household members.",
    href: "https://www.ancestry.com/search/collections/2442/records/161323863",
    grade: "Original enumeration",
  },
  {
    id: "candido-birth",
    label: "1923 birth: Cándido Reyes Díaz",
    detail: "Born 14 July 1923 in Humacao; parents Mauricio Reyes Martínez and Carmen Díaz García; both sets of grandparents named.",
    href: "https://www.ancestry.com/search/collections/9100/records/659141",
    grade: "Original civil record",
  },
  {
    id: "candido-death",
    label: "1948 death: Cándido Reyes López",
    detail: "The Humacao certificate names father Mauricio, mother Carmen, and brother Saturnino as informant. Its López surname and June birth date conflict with Cándido’s original birth act.",
    href: "https://www.ancestry.com/search/collections/9100/records/707995",
    grade: "Original civil record · identity resolved with conflicts",
  },
  {
    id: "teresa-death",
    label: "1927 death: Teresa Reyes Díaz",
    detail: "Died 1 June 1927 in Humacao at one day old; the act names Mauricio Reyes and Carmen Díaz as her parents.",
    href: "https://www.ancestry.com/search/collections/9100/records/683176",
    grade: "Original civil record",
  },
  {
    id: "heriberta-birth",
    label: "1913 birth: Heriberta Reyes Díaz",
    detail: "Naguabo act 593 gives 25 July 1913 and names Mauricio Reyes, Carmen Díaz, and all four grandparents. Her baptismal register gives a conflicting 16 March birth date.",
    href: "https://www.ancestry.com/search/collections/9100/records/9431655",
    grade: "Original civil record · date conflict retained",
  },
  {
    id: "heriberta-baptism",
    label: "1913 baptism: Heriberta Reyes Díaz",
    detail: "Baptized 31 August 1913 in Naguabo. The same parents and grandparents establish the identity; the register uses Anastasia Martínez and María de Reyes García.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSFS-59BS?view=fullText&lang=en&groupId=M9SP-6M8",
    grade: "Original parish register",
  },
  {
    id: "rafael-birth",
    label: "Puerto Rico civil registration: Rafael Vazquez y Peralez",
    detail: "Humacao registration 134; indexed February 1906; mother Carlina Peralez.",
    href: "https://www.ancestry.com/search/collections/9100/records/649515",
    grade: "Original image + index",
  },
  {
    id: "census-1910",
    label: "1910 Puerto Rico census",
    detail: "Anton Ruiz, Humacao; Rafael with Juan Vazquez y Rodriguez and Carlina Perales y Perez.",
    href: "https://www.ancestry.com/search/collections/7884/records/174417271",
    grade: "Original enumeration",
  },
  {
    id: "census-1920",
    label: "1920 Puerto Rico census",
    detail: "Camino Anton Ruiz, Humacao; Rafael remains in his parents’ household.",
    href: "https://www.ancestry.com/search/collections/6061/records/59358969",
    grade: "Original enumeration",
  },
  {
    id: "census-1930",
    label: "1930 Puerto Rico census",
    detail: "Mambiche, Humacao; Rafael is recorded as a single adult in Juan’s household.",
    href: "https://www.ancestry.com/search/collections/6224/records/113399940",
    grade: "Original enumeration",
  },
  {
    id: "juan-carlina-marriage",
    label: "1902 marriage: Juan Vázquez Rodríguez and Carlina Perales Pérez",
    detail: "Humacao marriage record; Juan’s parents Sotero Vázquez and Carmen Rodríguez; Carlina’s parents Marcelino Perales and Aurora Pérez.",
    href: "https://www.ancestry.com/search/collections/9100/records/1530270",
    grade: "Original civil record",
  },
  {
    id: "juan-baptism",
    label: "1878 baptism: Juan de la Rosa Vázquez",
    detail: "Born 30 August and baptized 13 October 1878 in Yabucoa; parents Sotero Vázquez and Carmen Rodríguez; grandparents Atilano Vázquez and Juana Rodríguez, and Cristóbal Rodríguez and María Pacheco.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSM8-3YYX?view=fullText&lang=en&groupId=M9SP-ZFM",
    grade: "Original parish register",
  },
  {
    id: "sotero-maria-eugenia-marriage",
    label: "1875 marriage: Sotero Vázquez and María Eugenia Rodríguez",
    detail: "Yabucoa entry 440 names Sotero’s parents Atilano Vázquez and Juana Rodríguez, and María Eugenia’s parents Cristóbal Rodríguez and Leonor Díaz. Its date is omitted but bracketed between 16 and 25 September.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSV2-2Q68-Z?view=fullText&lang=en&groupId=M99W-V63",
    grade: "Original parish register · date bracketed",
  },
  {
    id: "census-1910-sotero",
    label: "1910 census: Sotero Vázquez Rodríguez household",
    detail: "Anton Ruiz, Humacao, lines 6–9: Sotero, 63; wife María Rodríguez y Díaz, 66; sons Braulio, 18, and Francisco, 14. The 34-year marriage and seven children born and living match the 1875 marriage and 1916 child list, confirming the household while creating a major age conflict.",
    href: "https://www.ancestry.com/search/collections/7884/records/31747267",
    grade: "Original enumeration · age conflict retained",
  },
  {
    id: "victorio-baptism",
    label: "1881 baptism: Victorio Vázquez Rodríguez",
    detail: "Born 22 December 1880 and baptized 27 February 1881 in Yabucoa; parents Sotero Vázquez and María Eugenia Rodríguez; both sets of grandparents named.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSM8-3B5R?view=index&personArk=%2Fark%3A%2F61903%2F1%3A1%3A6DF9-RJYP&action=view&lang=en",
    grade: "Original parish register",
  },
  {
    id: "juan-del-carmen-birth",
    label: "1885 birth: Juan del Carmen Vázquez y Rodríguez",
    detail: "Born 24 May 1885 in Yabucoa; parents Sotero Vázquez and Eugenia Rodríguez. A tree attachment calls him Carmelo, but that later identity remains unproved.",
    href: "https://www.familysearch.org/ark:/61903/3:1:939D-7LSR-YJ?view=index&personArk=%2Fark%3A%2F61903%2F1%3A1%3AQVJV-DJHY&action=view&lang=en",
    grade: "Original civil record · later identity open",
  },
  {
    id: "francisco-birth",
    label: "1892 birth: Francisco Vázquez Rodríguez",
    detail: "Born 3 June 1892 in Yabucoa; parents Sotero Vázquez and Eugenia Rodríguez. The act reports paternal grandparents Atilano Vázquez and Juana Rodríguez already deceased, but Atilano’s own parish and civil deaths prove that notation wrong for him.",
    href: "https://www.familysearch.org/ark:/61903/3:1:939D-7LSD-DT?view=index&personArk=%2Fark%3A%2F61903%2F1%3A1%3AQVJV-6Q27&action=view&lang=en",
    grade: "Original civil record",
  },
  {
    id: "sotero-death",
    label: "1916 death: Sotero Vázquez Rodríguez",
    detail: "Died 31 May 1916 in Humacao. The act names wife Carmen Rodríguez, parents Atilano Vázquez and Juana Rodríguez, and seven living children: Juan, Juana, Victorio, Carmelo, Mauricio, Braulio, and Francisco.",
    href: "https://www.familysearch.org/ark:/61903/3:1:9Q97-YS6J-Q7Y?view=index&personArk=%2Fark%3A%2F61903%2F1%3A1%3AQVJS-FV93&action=view&lang=en",
    grade: "Original civil record",
  },
  {
    id: "maria-eugenia-death",
    label: "1933 death: María Eugenia Rodríguez Pacheco",
    detail: "Died 6 July 1933 in barrio Anton Ruiz, Humacao; widow of Sotero Vázquez. The act names parents Cristóbal Rodríguez and María Pacheco, and son Francisco Vázquez as informant. Its reported age conflicts with earlier records.",
    href: "https://www.ancestry.com/search/collections/9100/records/685901",
    grade: "Original civil record · age conflict retained",
  },
  {
    id: "atilano-juana-godparents",
    label: "1861 Yabucoa baptism: Atilano and Juana Regina as godparents",
    detail: "José León Carrasquillo’s baptism names Atilano Vázquez and Juana Regina Rodríguez as godparents, independently placing the couple together in Yabucoa.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSM8-3YFY?view=fullText&keywords=Atilano+V%C3%A1zquez%2CV%C3%A1zquez&lang=en&groupId=M9SP-ZXT",
    grade: "Original parish register",
  },
  {
    id: "maria-isidra-baptism",
    label: "1863 baptism: María Isidra Vázquez Rodríguez",
    detail: "Born 15 May and baptized 9 July 1863 in Yabucoa; daughter of Atilano Vázquez and Juana Regina Rodríguez. The entry names both sets of grandparents.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSM8-3YG3?view=fullText&keywords=Juana+Regina+Rodr%C3%ADguez&lang=en&groupId=M9SP-ZXT",
    grade: "Original parish register",
  },
  {
    id: "maria-eugenia-vazquez-baptism",
    label: "1879 baptism: María Eugenia, daughter of Atilano and Juana Paula",
    detail: "Born 20 May and baptized 22 June 1879 in Yabucoa. The two-page entry repeats Atilano’s parents, Máximo Vázquez and Josefa Rivera, supporting the same Atilano with a later partner, Juana Paula de Santiago.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSM8-399L-4?view=fullText&keywords=Atilano+V%C3%A1zquez%2CV%C3%A1zquez&lang=en&groupId=M9SP-ZFM",
    grade: "Original parish register · two-page entry",
  },
  {
    id: "maria-epifania-baptism",
    label: "1884 baptism: María Epifania Delgado Vázquez",
    detail: "The child’s mother was María Balbina Vázquez; maternal grandparents Atilano Vázquez and Juana Regina Rodríguez identify María Balbina as another daughter of that couple.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSM8-3BQZ?view=fullText&keywords=Juana+Regina+Rodr%C3%ADguez&lang=en&groupId=M9SP-ZFQ",
    grade: "Original parish register · two-page entry",
  },
  {
    id: "atilano-juana-marriage",
    label: "1849 marriage: Atilano Vázquez and Juana Rodríguez",
    detail: "Married 10 February 1849 in Yabucoa. The entry names Atilano’s parents Máximo Vázquez and Josefa de Rivera, and Juana’s parents the deceased Andrés and Francisca Díaz.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSM8-SQC9-X?view=fullText&keywords=Atilano%2CV%C3%A1zquez&lang=en",
    grade: "Original parish register",
  },
  {
    id: "maria-balbina-baptism",
    label: "1850 baptism: María Balbina Vázquez Rodríguez",
    detail: "Born 31 May and baptized 25 June 1850 in Yabucoa, daughter of Atilano Vázquez and Juana Rodríguez. The record names maternal grandparents Andrés Rodríguez and Francisca Díaz; the automated paternal-grandparent line is garbled and remains flagged for a careful reread.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSM8-SQ8Z-G",
    grade: "Original parish register · paternal line transcription caution",
  },
  {
    id: "maria-balbina-marriage",
    label: "1870 marriage: María Balbina Vázquez and Desiderio Rodríguez",
    detail: "Married 10 February 1870 in Yabucoa. María Balbina’s mother, Juana Rodríguez, is called deceased. A later child record uses Delgado for Desiderio, leaving a surname conflict.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSV2-2Q63-7?view=fullText&keywords=Atilano%2CJuana&lang=en",
    grade: "Original parish register · spouse surname conflict retained",
  },
  {
    id: "atilano-juana-paula-marriage",
    label: "1875 marriage: Atilano Vázquez and Juana Paula de Santiago",
    detail: "Married 18 December 1875. The record calls Atilano a native of Juncos and widower of Juana Regina Rodríguez; Juana Paula was from Humacao, daughter of Tomás de Santiago and Petronila Orellana.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSV2-2Q87-P?view=fullText&keywords=V%C3%A1zquez+Atilano&lang=en",
    grade: "Original parish register · two-page entry",
  },
  {
    id: "atilano-death",
    label: "1898 death: Atilano Vázquez",
    detail: "Died 3 June 1898 in Yabucoa at a reported age of 70. The parish entry names wife Juana de Santiago and parents Máximo Vázquez and Josefa Rivera; the civil registration agrees.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSV2-2Q4J-V?view=fullText&keywords=Atilano+V%C3%A1zquez%2CV%C3%A1zquez+Atilano&lang=en",
    grade: "Original parish and civil records",
  },
  {
    id: "francisca-vazquez-death",
    label: "1876 death: Francisca Vázquez",
    detail: "Died 14 February 1876 in Yabucoa, unmarried, reported age 22; legitimate daughter of Atilano Vázquez and Juana Rodríguez.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSV2-KQ95-J?view=fullText&keywords=Atilano+V%C3%A1zquez%2CV%C3%A1zquez%2CYabucoa&lang=en",
    grade: "Original parish register",
  },
  {
    id: "juana-jacinta-baptism",
    label: "1806 baptismal ceremonies: Juana Jacinta Vázquez",
    detail: "Born 16 August 1806 in Humacao, legitimate daughter of Máximo Vázquez and Josefa de Rivera. She was baptized at home because of danger of death; the parish supplied the ceremonies on 28 August. A computer index incorrectly calls the child Jesús.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSFS-K94J-H?view=fullText&keywords=Josefa%2CM%C3%A1ximo%2CRibera&lang=en",
    grade: "Original parish register · index name corrected",
  },
  {
    id: "juan-de-dios-baptism",
    label: "1819 baptism: Juan de Dios Vázquez",
    detail: "Born 9 March and baptized 14 March 1819 in Juncos, son of Máximo Vázquez, a native of Caguas, and Josefa de Ribera, a native of Humacao. The original corrects a computer index that shifted the event to 1813–1814.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSV2-MS7P-F?view=fullText&keywords=Juan%20de%20Dios%2CM%C3%A1ximo%20V%C3%A1zquez%2CRibera&lang=en",
    grade: "Original parish register · index dates corrected",
  },
  {
    id: "francisco-solano-death",
    label: "1878 death: Francisco Solano Vázquez Rivera",
    detail: "Died 30 December and buried 31 December 1878 in San Lorenzo, reported age 40; husband of Rita Rodríguez and son of Máximo Vázquez and Josefa Rivera. A computer transcript misread Solano as Polanco.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSV2-SS23-Z?view=fullText&keywords=Francisco%20V%C3%A1zquez%2CM%C3%A1ximo%20V%C3%A1zquez%2CJosefa%20Rivera&lang=en",
    grade: "Original parish register · OCR name corrected",
  },
  {
    id: "dolores-vazquez-baptism",
    label: "1879 baptism: Dolores, daughter of Francisco Solano",
    detail: "Born 1 December 1878 and baptized 7 March 1879 in San Lorenzo. Her baptism names Francisco Solano Vázquez and Rita Rodríguez as parents and Máximo Vázquez and Josefa Rivera as paternal grandparents.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSV2-9WQN-V?view=index&personArk=%2Fark%3A%2F61903%2F1%3A1%3A6DRH-1X1T&action=view&cc=1807092&lang=en",
    grade: "Original parish register + index",
  },
  {
    id: "mariana-vazquez-baptism",
    label: "1897 baptism: Mariana Vázquez de Santiago",
    detail: "Born 18 April 1896 and baptized 19 December 1897 in Cidra, daughter of Atilano Vázquez and Juana Santiago. The record repeats both grandparent pairs and uses Maximiliano as a later form of Máximo.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSVN-K9PZ-3?view=index&personArk=%2Fark%3A%2F61903%2F1%3A1%3A6Z4C-SCMK&action=view&cc=1807092&lang=en",
    grade: "Original parish register + index",
  },
  {
    id: "miguel-baptism",
    label: "1824 baptism: Miguel de los Santos Vázquez",
    detail: "Born 5 July and baptized 15 July 1824 in San Lorenzo, legitimate son of Máximo Vázquez and Josefa de Ribera and a documented brother of Atilano.",
    href: "https://www.familysearch.org/ark:/61903/1:1:6DXP-D6X1?lang=en",
    grade: "Original parish register + index",
  },
  {
    id: "andrea-death",
    label: "1866 death: Andrea Vázquez",
    detail: "Buried 19 November 1866 in Humacao and recorded as a legitimate daughter of Máximo Vázquez and Josefa Rivera.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSFS-GWZX-K?view=fullText&keywords=Josefa+Rivera%2CM%C3%A1ximo+V%C3%A1zquez&lang=en",
    grade: "Original parish register",
  },
  {
    id: "jose-maria-baptism",
    label: "1852 baptism: José María, son of María Vázquez",
    detail: "Born 12 September and baptized 3 October 1852 in San Lorenzo. Maternal grandparents Máximo Vázquez and Josefa de Rivera identify María as Atilano’s sister.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSV2-9W96-L?view=fullText&keywords=Josefa+de+Rivera%2CM%C3%A1ximo+V%C3%A1zquez&lang=en",
    grade: "Original parish register · two-page entry",
  },
  {
    id: "carlina-death",
    label: "1922 death: Carlina Perales Pérez",
    detail: "Humacao record naming husband Juan Vázquez, seven children including Rafael, and parents Marcelo Perales and Aurora Pérez.",
    href: "https://www.ancestry.com/search/collections/9100/records/681091",
    grade: "Original civil record",
  },
  {
    id: "juan-death",
    label: "1951 death: Juan Vázquez Rodríguez",
    detail: "Humacao record naming spouse Carlina Perales and parents Sotero Vázquez and María Eugenia Rodríguez; the mother’s name conflicts with Juan’s marriage record.",
    href: "https://www.ancestry.com/search/collections/9100/records/710658",
    grade: "Original civil record",
  },
  {
    id: "pedro-death",
    label: "1918 death: Pedro Reyes",
    detail: "Humacao record naming wife Ana Martínez and their children, including Mauricio.",
    href: "https://www.ancestry.com/search/collections/9100/records/678330",
    grade: "Original civil record",
  },
  {
    id: "ana-death",
    label: "1918 death: Ana Martínez",
    detail: "Died 21 March 1918 in Humacao, about age 60; widow of Pedro Reyes; children Isabel, Natalio, Mauricio, and Juliano named.",
    href: "https://www.ancestry.com/search/collections/9100/records/45678048",
    grade: "Original civil record",
  },
  {
    id: "lope-death",
    label: "1929 death: Lope Díaz Figueroa",
    detail: "Humacao record naming wife Reyes García and parents Manuel Díaz and Carmen Figueroa.",
    href: "https://www.ancestry.com/search/collections/9100/records/684632",
    grade: "Original civil record",
  },
  {
    id: "reyes-garcia-death",
    label: "1933 death: Reyes García Olivero",
    detail: "Humacao record naming parents Bautista García and Carmen Olivero, with Naguabo birthplaces.",
    href: "https://www.ancestry.com/search/collections/9100/records/686138",
    grade: "Original civil record",
  },
  {
    id: "secundino-baptism",
    label: "1903 baptism: Secundino Díaz García",
    detail: "Born 23 May and baptized 4 July 1903 in Humacao; parents Lope Díaz and María de Reyes García; all four grandparents named. The index’s Decundino is a transcription error.",
    href: "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSFS-VSD5-B?view=fullText&lang=en&groupId=M993-W4S",
    grade: "Original parish register",
  },
  {
    id: "braulio-marriage-1915",
    label: "1915 marriage: Braulio Vázquez Rodríguez and Cayetana Vázquez",
    detail: "Braulio’s original Humacao marriage record names his parents Sotero Vázquez and María Eugenia Rodríguez.",
    href: "https://www.ancestry.com/search/collections/9100/records/746471",
    grade: "Original civil record",
  },
  {
    id: "braulio-marriage-1923",
    label: "1923 marriage: Braulio Vázquez Rodríguez and Felicita Mendoza Santiago",
    detail: "A second original marriage record again names Sotero and María Eugenia. This supports Braulio’s parentage but does not resolve Juan’s mother.",
    href: "https://www.ancestry.com/search/collections/9100/records/748917",
    grade: "Original civil record",
  },
  {
    id: "marcelino-death",
    label: "1891 death: Marcelino Perales y Medina",
    detail: "Two-page Naguabo act: died 13 May 1891, about age 50; wife Aurora Pérez; parents recorded as Abal or Abel Perales and Vicenta Medina.",
    href: "https://www.ancestry.com/search/collections/9100/records/4607227",
    grade: "Original civil record",
  },
  {
    id: "juan-perales-marriage",
    label: "1904 marriage: Juan Perales Pérez",
    detail: "A son of Marcelo Perales and Aurora Pérez married Manuela in Humacao on 28 August 1904.",
    href: "https://www.ancestry.com/search/collections/9100/records/1531375",
    grade: "Original civil record",
  },
  {
    id: "catalina-perales-death",
    label: "1958 death: Catalina Perales Pérez",
    detail: "Naguabo record naming Marcelino Perales and Aurora Pérez; Catalina is a separate daughter from Carlina.",
    href: "https://www.ancestry.com/search/collections/9100/records/4626202",
    grade: "Original civil record",
  },
  {
    id: "leocadio-perales-death",
    label: "1944 death: Leocadio Perales Pérez",
    detail: "Gurabo record naming Marcelo Perales and Aurora Pérez; reported age gives an estimated 1884 birth.",
    href: "https://www.ancestry.com/search/collections/9100/records/3812242",
    grade: "Original civil record",
  },
  {
    id: "perales-sibling-indexes",
    label: "Perales–Pérez sibling record cluster",
    detail: "Additional civil records name Martina, Hilaria, Marcolina, and Francisca as children of Marcelino or Marcelo Perales and Aurora Pérez. Extreme reported ages remain provisional.",
    href: "https://www.ancestry.com/search/collections/9100/",
    grade: "Original records + derivative indexes",
  },
  {
    id: "census-1935-aurora",
    label: "1935 Puerto Rico social census: Aurora Pérez and Hilaria Perales",
    detail: "Río Blanco, Naguabo; widowed Aurora, reported age 95, is recorded as the mother of Ilaria or Hilaria Perales, widow of Rotger.",
    href: "https://www.ancestry.com/search/collections/2404/records/1583597",
    grade: "Original enumeration",
  },
  {
    id: "census-1940-aurora",
    label: "1940 census: Aurora Pérez, widow of Perales",
    detail: "Río Blanco, Naguabo; Aurora, reported age 99, again appears as the mother of Ilaria or Hilaria Perales. The image corrects the index's surname error.",
    href: "https://www.ancestry.com/search/collections/2442/records/162855393",
    grade: "Original enumeration",
  },
  {
    id: "census-1950",
    label: "1950 United States census",
    detail: "Rafael and Cruz together on East 109th Street, Manhattan.",
    href: "https://www.ancestry.com/search/collections/62308/records/294017627",
    grade: "Original enumeration",
  },
  {
    id: "cemetery",
    label: "Rosedale & Rosehill official cemetery lookup",
    detail: "Both burials in Rosedale plot WIN4T-22-11, Linden, New Jersey.",
    href: "https://www.rosedale-rosehill.com/name-lookup",
    grade: "Official cemetery database",
  },
  {
    id: "findagrave-cruz",
    label: "Cruz Vasquez memorial 122157535",
    detail: "Independently reports Rosedale & Rosehill and plot WIN4T-22-11.",
    href: "https://www.findagrave.com/memorial/122157535/cruz-vasquez",
    grade: "User-contributed memorial",
  },
  {
    id: "nj-death-index",
    label: "New Jersey Death Index",
    detail: "Reviewed as a negative search for the 1984 and 1998 deaths.",
    href: "https://www.newjerseydeathindex.com/",
    grade: "Official index images",
  },
];

export const familyCouples = [
  {
    id: "mauricio-carmen",
    branch: "Cruz’s parents",
    couple: "Mauricio Reyes Martínez + Carmen Díaz García",
    status: "documented" as const,
    connection: "Parents of Cruz Reyes Díaz",
    people: [
      {
        name: "Mauricio Reyes Martínez",
        birth: "About 1881–1882 · Humacao, Puerto Rico",
        death: "Strong candidate: 29 May 1977 · Bayamón",
      },
      {
        name: "Carmen Díaz García",
        birth: "About 1887–1889 · Puerto Rico",
        death: "Not yet found",
      },
    ],
    children: [
      "Juana",
      "Ruperto",
      "Heriberta (civil birth: 25 Jul 1913; baptism record: 16 Mar 1913)",
      "Cruz",
      "Belén",
      "Angelina (1930 census)",
      "Aurora (1940 census)",
      "Cándido (1923–1948)",
      "Teresa (died as an infant in 1927)",
      "Saturnino",
      "Tomás (1930 census)",
      "Julio César (1935–40 censuses)",
    ],
    childNote:
      "The list combines the 1910–1940 households with Cándido’s birth and Teresa’s death. Angelina may be Aurora, and Tomás may be Julio César; neither pair is merged without a direct record.",
  },
  {
    id: "juan-carlina",
    branch: "Rafael’s parents",
    couple: "Juan Vázquez Rodríguez + Carlina Perales Pérez",
    status: "documented" as const,
    connection: "Parents of Rafael Vázquez y Perales",
    people: [
      {
        name: "Juan de la Rosa Vázquez Rodríguez",
        birth: "30 August 1878 · Yabucoa, Puerto Rico",
        death: "22 December 1951 · Humacao, Puerto Rico",
      },
      {
        name: "Carlina Perales Pérez",
        birth: "About 1881–1882 · Naguabo, Puerto Rico",
        death: "31 May 1922 · Humacao, Puerto Rico",
      },
    ],
    children: ["Inés", "Juana", "Josué", "Marcelo", "Paulo or Paula", "Rafael", "Ramón"],
    childNote:
      "Carlina’s death act says seven children survived her. The names above come from the family export and census work; individual civil records remain a secondary search.",
  },
  {
    id: "pedro-ana",
    branch: "Mauricio’s parents",
    couple: "Pedro Reyes + Ana or Anastasia Martínez",
    status: "documented" as const,
    connection: "Her paternal grandparents",
    people: [
      {
        name: "Pedro Reyes",
        birth: "About 1842–1850 · Humacao, Puerto Rico · conflicting ages",
        death: "3 January 1918 · Humacao, Puerto Rico",
      },
      {
        name: "Ana or Anastasia Martínez",
        birth: "About 1854–1858 · Humacao, Puerto Rico",
        death: "21 March 1918 · Humacao, Puerto Rico",
      },
    ],
    children: ["Isabel", "Natalio", "Benito Isabel", "Mauricio", "Julián or Juliano"],
    childNote:
      "Ana reported seven children born and four living in 1910, so this remains an incomplete cluster. Benito Isabel is not merged with the later Isabel. Heriberta’s 1913 baptism uses Anastasia; the civil records use Ana.",
  },
  {
    id: "ramon-ines",
    branch: "Pedro’s parents",
    couple: "Ramón Reyes + Inés Castro",
    status: "documented" as const,
    connection: "Her paternal great-grandparents",
    people: [
      {
        name: "Ramón Reyes",
        birth: "Not yet found",
        death: "Not yet found",
      },
      {
        name: "Inés Castro",
        birth: "Not yet found",
        death: "Not yet found",
      },
    ],
    children: ["Pedro Reyes"],
    childNote:
      "Mauricio’s 1882 baptism and Benito Isabel’s 1877 baptism independently name Ramón and Inés as Pedro’s parents. Their own life records are the next target.",
  },
  {
    id: "damaso-maria",
    branch: "Ana’s parents",
    couple: "Dámaso Martínez + María Rivera",
    status: "documented" as const,
    connection: "Her paternal great-grandparents",
    people: [
      {
        name: "Dámaso Martínez",
        birth: "Not yet found",
        death: "Not yet found",
      },
      {
        name: "María Rivera",
        birth: "Not yet found",
        death: "Not yet found",
      },
    ],
    children: ["Ana or Anastasia Martínez"],
    childNote:
      "Mauricio’s 1882 baptism clearly names this pair. A 1877 sibling baptism repeats Dámaso but leaves María’s surname difficult to read; the conflict remains visible.",
  },
  {
    id: "lope-reyes",
    branch: "Carmen’s parents",
    couple: "Lope Díaz Figueroa + Reyes García Olivero",
    status: "documented" as const,
    connection: "Her maternal grandparents",
    people: [
      {
        name: "Lope Díaz Figueroa",
        birth: "About 1858–1859 · Puerto Rico",
        death: "23 March 1929 · Humacao, Puerto Rico",
      },
      {
        name: "Reyes García Olivero",
        birth: "About 1862–1863 · Puerto Rico",
        death: "28 March 1933 · Humacao, Puerto Rico",
      },
    ],
    children: ["Carmen", "Saturnino", "Paulino", "Secundino (born 23 May 1903)"],
    childNote:
      "Secundino’s baptism directly names Lope and María de Reyes García and all four grandparents. The register calls Reyes’s mother Dolores Olivero; her death record says Carmen Olivero.",
  },
  {
    id: "sotero-rodriguez",
    branch: "Juan’s parents and siblings",
    couple: "Sotero Vázquez + María Eugenia Rodríguez",
    status: "documented" as const,
    connection: "Married in Yabucoa in September 1875; records also use Eugenia and Carmen for the mother of this child cluster",
    people: [
      {
        name: "Sotero Vázquez Rodríguez",
        birth: "Yabucoa · reported ages imply about 1847 or about 1860",
        death: "31 May 1916 · Humacao, Puerto Rico",
      },
      {
        name: "María Eugenia Rodríguez Pacheco",
        birth: "Yabucoa · reported ages conflict from about 1835 to 1858",
        death: "6 July 1933 · Humacao, Puerto Rico",
      },
    ],
    children: [
      "Juan de la Rosa — born 30 Aug 1878; mother recorded as Carmen",
      "Juana — living in 1916; birth not yet found",
      "Victorio — born 22 Dec 1880; mother recorded as María Eugenia",
      "Carmelo — living in 1916; may be Juan del Carmen, born 24 May 1885",
      "Mauricio — living in 1916; birth not yet found",
      "Braulio — two marriages name mother María Eugenia",
      "Francisco — born 3 Jun 1892; mother recorded as Eugenia",
    ],
    childNote:
      "The 1910 census records Sotero and María with sons Braulio and Francisco, a 34-year marriage, and seven children born and living. Sotero’s 1916 death names all seven children and wife Carmen. María Eugenia’s 1933 death names her as Sotero’s widow and their son Francisco as informant. The same husband, child cluster, and recurring Rodríguez grandparents make Carmen, Eugenia, and María Eugenia strong name variants for one woman, but the profiles remain separate until a record explicitly joins those given names.",
  },
  {
    id: "atilano-juana",
    branch: "Sotero’s parents",
    couple: "Atilano Vázquez + Juana Regina Rodríguez",
    status: "documented" as const,
    connection: "Married 10 February 1849 in Yabucoa; parents of Sotero and at least three documented daughters",
    people: [
      {
        name: "Atilano Vázquez",
        birth: "About 1828 · Juncos, Puerto Rico · death-age estimate",
        death: "3 June 1898 · Yabucoa, Puerto Rico",
      },
      {
        name: "Juana Regina Rodríguez",
        birth: "Puerto Rico · exact date and place not yet found",
        death: "After 9 Jul 1863 and before 10 Feb 1870",
      },
    ],
    children: [
      "Sotero Vázquez",
      "Francisca — died 14 Feb 1876, age 22",
      "María Isidra — born 15 May 1863",
      "María Balbina — born 31 May 1850; married Desiderio Rodríguez on 10 Feb 1870",
    ],
    childNote:
      "Juana was alive for María Isidra’s 1863 baptism and called deceased in María Balbina’s 1870 marriage. The available Yabucoa burial item begins in 1871, after Juana’s death window. A grandson’s 1892 birth act mistakenly calls Atilano deceased; his matching parish and civil deaths establish 1898. María Balbina’s marriage calls the groom Desiderio Rodríguez, while an 1884 child baptism calls him Desiderio Delgado.",
  },
  {
    id: "atilano-juana-paula",
    branch: "Atilano’s later family",
    couple: "Atilano Vázquez + Juana Paula de Santiago",
    status: "documented" as const,
    connection: "Married 18 December 1875 in Yabucoa",
    people: [
      {
        name: "Atilano Vázquez",
        birth: "About 1828 · Juncos, Puerto Rico · death-age estimate",
        death: "3 June 1898 · Yabucoa, Puerto Rico",
      },
      {
        name: "Juana Paula de Santiago",
        birth: "Humacao, Puerto Rico · exact date not yet found",
        death: "Not yet found",
      },
    ],
    children: [
      "María Eugenia — born 20 May 1879 in Yabucoa",
      "Mariana — born 18 Apr 1896; baptized 19 Dec 1897 in Cidra",
    ],
    childNote:
      "The marriage calls Atilano the widower of Juana Regina Rodríguez and names Juana Paula’s parents as Tomás de Santiago and Petronila Orellana. Both daughters’ baptisms repeat the same parent and grandparent cluster.",
  },
  {
    id: "maximo-josefa",
    branch: "Atilano’s parents",
    couple: "Máximo Vázquez + Josefa Rivera",
    status: "documented" as const,
    connection: "Parents of Atilano; eight children now documented through original records",
    people: [
      {
        name: "Máximo Vázquez",
        birth: "Caguas, Puerto Rico · native place recorded in 1819; date not found",
        death: "Not yet found",
      },
      {
        name: "Josefa Rivera",
        birth: "Humacao, Puerto Rico · native place recorded in 1819; date not found",
        death: "Not yet found",
      },
    ],
    children: [
      "Juana Jacinta — born 16 Aug 1806 in Humacao",
      "Andrea — born about 1816; buried 19 Nov 1866 in Humacao",
      "Juan de Dios — born 9 Mar 1819 in Juncos; died in 1820",
      "Miguel de los Santos — born 5 Jul 1824 in San Lorenzo",
      "Atilano — born about 1828 in Juncos",
      "Francisco Solano — born about 1838; died 30 Dec 1878 in San Lorenzo",
      "Manuel — married 14 Feb 1846 in Yabucoa",
      "María — documented through children born in Humacao and San Lorenzo",
      "Tomasa — probable daughter; died in 1889, age conflict unresolved",
    ],
    childNote:
      "Eight children are supported by original records naming the exact parent pair. Juan de Dios’s 1819 baptism now resolves his earlier provisional identity. Francisco Solano is supported by his death and his daughter Dolores’s baptism; Polanco is an OCR error. Tomasa alone remains provisional because her reported age conflicts with Juan de Dios’s known birth.",
  },
  {
    id: "andres-francisca",
    branch: "Juana Regina’s parents",
    couple: "Andrés [Rodríguez] + Francisca Díaz",
    status: "documented" as const,
    connection: "Parents of Juana Regina Rodríguez",
    people: [
      {
        name: "Andrés [Rodríguez]",
        birth: "Not yet found",
        death: "Not yet found",
      },
      {
        name: "Francisca Díaz",
        birth: "Not yet found",
        death: "Not yet found",
      },
    ],
    children: ["Juana Regina Rodríguez"],
    childNote:
      "Their granddaughter María Isidra’s 1863 baptism gives Andrés without a surname and Francisca Díaz. Rodríguez is inherited from their daughter and remains bracketed.",
  },
  {
    id: "marcelino-aurora",
    branch: "Carlina’s parents",
    couple: "Marcelino Perales y Medina + Aurora Pérez",
    status: "documented" as const,
    connection: "Maternal grandparents of Rafael Vázquez y Perales",
    people: [
      {
        name: "Marcelino Perales y Medina",
        birth: "About 1841 · Naguabo, Puerto Rico",
        death: "13 May 1891 · Naguabo, Puerto Rico",
      },
      {
        name: "Aurora Pérez",
        birth: "About 1840–1841 · late-life census estimate",
        death: "After 5 April 1940 · exact date not yet found",
      },
    ],
    children: [
      "Hilaria",
      "Juan",
      "Catalina",
      "Marcolina",
      "Carlina",
      "Leocadio",
      "Francisca",
      "Martina",
    ],
    childNote:
      "Multiple civil records repeat the same parent pair. The 1935 and 1940 censuses place Aurora with daughter Hilaria or Ilaria and suggest Hilaria was born about 1889–1890; exact birth records are still needed.",
  },
];

export const openCases = [
  {
    id: "VR-01",
    title: "The secondhand Pastora story",
    conflict: "Cruz’s daughter remembers being told that Pastora may have been her mother’s name, but does not remember Cruz using it. Every identified record uses Cruz. The Gurabo index also lists a matching-era Cruz Reyes in book 15, folio 18 verso, but the surviving page is damaged and the indexed entry is not legible.",
    next: "Seek a duplicate register, sacramental certificate, alternate filming, or parish archive lookup for book 15, folio 18 verso that names the child and parents.",
  },
  {
    id: "VR-02",
    title: "Rafael’s exact birth day",
    conflict: "February 1906 vs. the remembered 24 October",
    next: "Obtain a legible certified copy or expert transcription of Humacao registration 134.",
  },
  {
    id: "VR-03",
    title: "The exact death records",
    conflict: "Rafael’s family date is 30 December 1984; a weak derivative gives 1 December.",
    next: "Obtain both NYC death certificates and the cemetery interment cards.",
  },
  {
    id: "VR-04",
    title: "Mauricio Reyes’s death and mother",
    conflict: "The strong 1977 candidate matches Mauricio’s full name, age, Humacao birthplace, father Pedro, and widowed status. A nurse supplied mother María rather than the documented Ana and did not know his spouse; the family export says 1982.",
    next: "His 1882 baptism now confirms Ana as his mother. Find an obituary, burial, or another family-informed later record before merging the 1977 death.",
  },
  {
    id: "VR-05",
    title: "Juan Vázquez’s mother",
    conflict: "Juan’s records say Carmen or María Eugenia. María Eugenia’s 1933 death confirms her as Sotero’s widow and names their son Francisco as informant. Together with the child records, one woman using Carmen, Eugenia, and María Eugenia remains the strongest explanation, but no record yet gives a combined name.",
    next: "Find birth or baptism records for Juana, Mauricio, and Braulio, plus María Eugenia’s baptism or marriage preliminaries and a record that explicitly joins Carmen with Eugenia before merging the profiles.",
  },
  {
    id: "VR-06",
    title: "The Rodríguez maternal surname",
    conflict: "The same maternal grandmother appears as Leonor or Leonarda Díaz, María Pacheco, Leonarda Pacheco, and María Leonarda Díaz. María Eugenia’s own 1933 death confirms the Pacheco form, but no reviewed record states the full Díaz–Pacheco combination.",
    next: "Seek María Eugenia’s baptism or marriage preliminaries. Keep Díaz and Pacheco unmerged until an original bridges them.",
  },
  {
    id: "VR-07",
    title: "Aurora Pérez’s death and parents",
    conflict: "She was alive in Río Blanco on 5 April 1940. Her reported ages suggest about 1840–1841, but neither her birth nor death has been found.",
    next: "Search Naguabo and nearby municipalities after April 1940 under Pérez, Perales, and widow-of-Perales forms.",
  },
  {
    id: "VR-08",
    title: "Two Reyes sibling name pairs",
    conflict: "Angelina in 1930 may be Aurora in 1940; infant Tomás in 1930 may be Julio César in 1935 and 1940. Compatible ages are not enough to merge either pair.",
    next: "Find their Humacao birth, baptism, marriage, or death records using Mauricio Reyes and Carmen Díaz as parent anchors.",
  },
  {
    id: "VR-09",
    title: "Sotero’s baptism and age",
    conflict: "The securely identified 1910 household reports Sotero as 63, implying about 1847; his 1916 death reports 56, implying about 1860. The earlier estimate predates his parents’ 1849 marriage, while the later makes him about 15 at his own 1875 marriage. The Yabucoa item for 1848–1856 was reviewed image by image without a defensible match.",
    next: "Seek an unfilmed register, duplicate parish book, diocesan copy, archive inventory, or neighboring-parish baptism for the collection gaps in 1843–1847 and 1857–1860.",
  },
  {
    id: "VR-10",
    title: "Atilano’s baptism",
    conflict: "His 1875 marriage says he was from Juncos, and his 1898 death at reported age 70 implies about 1828. Neither the full-text index nor a direct image-by-image scan of the expected 1828–1829 Juncos pages produced a defensible baptism.",
    next: "Inspect original Juncos index pages for omissions and neighboring San Lorenzo baptisms around 1827–1829 using Máximo Vázquez and Josefa de Ribera as parent anchors.",
  },
  {
    id: "VR-11",
    title: "Juana Regina’s exact death",
    conflict: "She was alive on 9 July 1863 and called deceased on 10 February 1870. Focused searches found no death, and the reviewed Yabucoa burial item starts in July 1871, after the entire target window.",
    next: "Find an earlier Yabucoa burial book, duplicate parish register, diocesan copy, or archive inventory covering July 1863 through February 1870.",
  },
  {
    id: "VR-12",
    title: "Desiderio Rodríguez or Delgado",
    conflict: "María Balbina’s 1870 marriage calls her groom Desiderio Rodríguez. The 1884 baptism of apparent daughter María Epifania calls the father Desiderio Delgado.",
    next: "Find María Epifania’s civil birth and records naming Desiderio’s parents, age, and residence before merging the surname forms.",
  },
  {
    id: "VR-13",
    title: "Máximo and Josefa’s full child cluster",
    conflict: "Eight children are now documented through the exact parent pair: Juana Jacinta, Andrea, Juan de Dios, Miguel, Atilano, Francisco Solano, Manuel, and María. Tomasa remains probable because her reported age conflicts with Juan de Dios’s known 1819 birth. The long 1806-to-about-1838 child span also needs testing.",
    next: "Find Máximo and Josefa’s marriage before 16 August 1806, Máximo’s baptism in Caguas, Josefa’s baptism in Humacao, and another record that establishes Tomasa’s age and birthplace.",
  },
  {
    id: "VR-14",
    title: "Mauricio’s exact birth year",
    conflict: "His 23 February 1882 baptism reports a 22 September birth but says it occurred “this year,” which would place the birth after the baptism. An 1881 birth is likely, not proven.",
    next: "Find the civil birth, duplicate baptism, parish index, confirmation, or marriage-preparation record before assigning 22 September 1881 as exact.",
  },
  {
    id: "VR-15",
    title: "Ana’s baptism and maternal surname",
    conflict: "Mauricio’s 1882 baptism clearly names Dámaso Martínez and María Rivera as Ana’s parents. A 1877 sibling baptism repeats Dámaso but leaves María’s surname difficult to read. An 1844 Ana with the same parent names is too old to fit Ana’s ages in 1910 and 1918.",
    next: "Search Humacao baptisms about 1854–1858 and the Pedro–Ana marriage around 1874–1875. Retain the 1844 child without merging her.",
  },
  {
    id: "VR-16",
    title: "Benito Isabel and Isabel",
    conflict: "A 1877 baptism records a son named Benito Isabel. Ana’s 1918 death names a living child Isabel. The shared name element does not prove one identity.",
    next: "Find civil births, baptisms, marriages, or deaths for both children using Pedro Reyes and Ana Martínez as parent anchors.",
  },
];

export const negativeSearches = [
  "No confident Cruz or Rafael match appeared in the reviewed New Jersey death-index image sets for 1984 and 1998.",
  "The New York State death index returned no match, but that index does not reliably cover New York City and cannot settle the question.",
  "No Rafael memorial matching the shared plot was found on Find a Grave; the official cemetery database remains the stronger burial source.",
  "Sotero’s death, several child records, and María Eugenia’s own 1933 death strongly favor Carmen, Eugenia, and María Eugenia as one woman’s name variants, but no original yet states that bridge explicitly.",
  "All 146 images in the Yabucoa baptism item for 1848–1856 were manually reviewed without a defensible Sotero match. FamilySearch identifies the preceding item as 1838–1842 and has no baptism item after 1856, leaving 1843–1847 and 1857–1860 as collection gaps rather than remaining pages.",
  "An 1861 baptism of Sotero Lebrón is not Sotero Vázquez Rodríguez. The full page is retained as a rejected candidate.",
  "An 1898 death for a roughly 50-year-old Sotero Vázquez belongs to a son of Tomás and Rosa, not the son of Atilano and Juana. The image is retained as a rejected same-name candidate.",
  "An 1897 burial indexed as male Eladia Vázquez and attached to a Juan Vázquez tree profile has conflicting name, age, and identity signals. It is retained but not added as a confirmed child.",
  "No Juana Regina death appeared in focused exact-name searches. The reviewed Yabucoa burial item begins in July 1871, after her 1863–1870 death window, so this remains a coverage gap.",
  "Atilano’s baptism was not found in either the full-text index or a direct scan of the expected 1828–1829 Juncos pages. A damaged 1846 page naming Don Atilano del Rosario Vázquez as a godfather is retained only as a candidate naming clue.",
  "A 1942 death for Aurora Monserrate Pérez belongs to the widow of Marcelo Pérez, not the wife of Marcelino Perales; it was captured and rejected.",
  "No Pastora Reyes entry appears in the reviewed Gurabo baptism-index pages. A Cruz Reyes entry points to book 15, folio 18 verso, but the damaged register image does not expose the child or parents.",
  "The 1844 Humacao baptism of an Ana Martínez with parents Dámaso Martínez and María Rivera is retained but rejected as the direct Ana because it is 11–14 years earlier than her ages in the 1910 census and 1918 death act.",
  "Focused searches for Pedro Reyes and Juana Villafañe’s marriage and for Juana’s death did not produce a defensible exact match; two children’s original death records nevertheless confirm the parent pair.",
];

export const nameVariants = [
  {
    person: "Cruz Reyes Díaz Vasquez",
    forms: "Cruz Reyes Díaz · Cruz Reyes · Cruz Vasquez · Cruz Vázquez · Pastora Reyes (secondhand oral-history lead only)",
    conclusion: "Cruz Reyes Díaz is the documented civil form, and every identified later record uses Cruz. Her daughter remembers being told that Pastora may have been her mother’s name, but does not remember her using it. The damaged Gurabo folio does not reveal enough to identify the indexed Cruz Reyes conclusively.",
  },
  {
    person: "Rafael Vázquez y Perales",
    forms: "Rafael Vazquez · Raphael Vasquez · Rafael Vazquez y Peralez",
    conclusion: "Vázquez y Perales is the fullest Puerto Rico-style form currently supported.",
  },
  {
    person: "Carmen Díaz García",
    forms: "Carmen Díaz García · Carmen Reyes",
    conclusion: "Díaz García is her documented birth name. Belén was a daughter in the household, not Carmen’s maiden name.",
  },
  {
    person: "Carlina Perales y Pérez",
    forms: "Carlina Peralez · Carlina Perales de Vazquez · Cathelina/Catalina Pérez or López",
    conclusion: "The 1902 marriage and 1922 death confirm Carlina Perales Pérez; neither supports López.",
  },
  {
    person: "Juan de la Rosa Vázquez Rodríguez",
    forms: "Juan de la Rosa Vázquez · Juan Vázquez Rodríguez · Juan Vázquez y Rodríguez · Juan Ramón Vázquez",
    conclusion: "The baptism documents Juan de la Rosa. Adult records document Vázquez Rodríguez. Ramón remains a family search variant not yet found in a record.",
  },
  {
    person: "Heriberta Reyes Díaz",
    forms: "Heriberta Reyes Díaz · Eriberta Reyes Díaz",
    conclusion: "The civil birth and baptism use Heriberta; censuses use Eriberta. The records identify one woman but disagree on whether she was born 16 March or 25 July 1913.",
  },
  {
    person: "Ana or Anastasia Martínez",
    forms: "Ana Martínez · Anastasia Martínez",
    conclusion: "Civil records use Ana. Her granddaughter Heriberta’s baptism uses Anastasia for the same wife of Pedro Reyes.",
  },
  {
    person: "Reyes García Olivero",
    forms: "Reyes García Olivero · María de Reyes García",
    conclusion: "Both forms refer to Lope Díaz’s wife. Her mother is recorded as Carmen Olivero on the death act and Dolores Olivero on Secundino’s baptism; that conflict remains open.",
  },
  {
    person: "Juana Regina Rodríguez",
    forms: "Juana Regina Rodríguez · Juana Rodríguez",
    conclusion: "The 1861, 1863, 1875, and 1884 parish entries supply Regina. Her 1849 marriage and later records often shorten the name to Juana Rodríguez.",
  },
  {
    person: "Two different María Eugenias",
    forms: "María Eugenia Rodríguez Pacheco · María Eugenia Vázquez de Santiago",
    conclusion: "Sotero’s wife and widow is María Eugenia Rodríguez Pacheco. A separate child named María Eugenia was born in 1879 to Atilano Vázquez and Juana Paula de Santiago; she was Sotero’s likely half-sister, not his wife.",
  },
  {
    person: "Máximo Vázquez",
    forms: "Máximo Vázquez · Maximino Vázquez · Maximiliano Vázquez",
    conclusion: "Máximo is the recurring early-register form. Later descendant records and indexes use Maximino or Maximiliano; the repeated spouse and family cluster support name variants, not separate grandfathers.",
  },
  {
    person: "Francisco Solano Vázquez Rivera",
    forms: "Francisco Solano Vázquez Rivera · Francisco Polanco Vázquez Rivera",
    conclusion: "Solano is supported by the original death margin and his daughter Dolores’s baptism. Polanco is an automated handwriting transcription error.",
  },
];

export const updates = [
  {
    date: "23 Jul 2026",
    text: "Recorded the family account, including uncertain names and dates.",
  },
  {
    date: "23 Jul 2026",
    text: "Identified the couple through their Manhattan marriage, 1950 household, and matching parent names.",
  },
  {
    date: "23 Jul 2026",
    text: "Reconstructed Rafael’s Humacao childhood household in the 1910, 1920, and 1930 censuses.",
  },
  {
    date: "23 Jul 2026",
    text: "Confirmed both burials in the same Rosedale plot at Rosedale & Rosehill Cemetery.",
  },
  {
    date: "23 Jul 2026",
    text: "Created separate pages for the public summary and the research notes.",
  },
  {
    date: "24 Jul 2026",
    text: "Captured Cruz’s 1915 Gurabo birth record and corrected the public birthplace.",
  },
  {
    date: "24 Jul 2026",
    text: "Linked the Reyes–Díaz family across the 1910, 1920, and 1930 censuses and identified Belén as Cruz’s sister.",
  },
  {
    date: "24 Jul 2026",
    text: "Found the 1902 and 1907 parental marriages and original death records that carry several branches back to the mid-1800s.",
  },
  {
    date: "24 Jul 2026",
    text: "Archived record pages, viewer images, and available original downloads in the private evidence store.",
  },
  {
    date: "24 Jul 2026",
    text: "Added birth and death fields for every direct-line parent and grandparent, including explicit not-yet-found entries.",
  },
  {
    date: "24 Jul 2026",
    text: "Captured Ana Martínez’s death, both pages of Marcelino Perales’s death act, two Braulio marriages, and the Perales–Pérez sibling cluster.",
  },
  {
    date: "24 Jul 2026",
    text: "Recorded the daughter’s secondhand Pastora recollection as an unverified oral-history lead, separate from the consistently documented name Cruz.",
  },
  {
    date: "24 Jul 2026",
    text: "Found Aurora Pérez in Río Blanco in 1935 and 1940 with daughter Hilaria or Ilaria, establishing that Aurora lived past 5 April 1940.",
  },
  {
    date: "24 Jul 2026",
    text: "Extended Mauricio and Carmen’s household through the 1935 and 1940 censuses; Cruz was still in Collores on 4 April 1940.",
  },
  {
    date: "24 Jul 2026",
    text: "Confirmed Cándido’s 14 July 1923 birth and resolved his 1948 death despite later surname and birth-date errors.",
  },
  {
    date: "24 Jul 2026",
    text: "Identified infant Teresa Reyes Díaz and separated the unresolved Angelina/Aurora and Tomás/Julio name questions.",
  },
  {
    date: "24 Jul 2026",
    text: "Located the Gurabo baptism-index entry Cruz Reyes, book 15, folio 18 verso, and captured the exact damaged folio without overstating the identification.",
  },
  {
    date: "24 Jul 2026",
    text: "Confirmed Heriberta Reyes Díaz with both her civil birth and baptism, retaining the records’ 16 March versus 25 July 1913 date conflict.",
  },
  {
    date: "24 Jul 2026",
    text: "Found Secundino Díaz García’s 1903 baptism, expanding the Díaz–García sibling cluster and documenting several grandparent name variants.",
  },
  {
    date: "24 Jul 2026",
    text: "Found Juan de la Rosa Vázquez’s 1878 Yabucoa baptism and Sotero Vázquez’s 1875 marriage, extending the direct line to Atilano Vázquez and Juana Rodríguez.",
  },
  {
    date: "24 Jul 2026",
    text: "Found Sotero Vázquez Rodríguez’s 1916 death act, including wife Carmen Rodríguez and seven living children.",
  },
  {
    date: "24 Jul 2026",
    text: "Captured original records for Victorio, Juan del Carmen, and Francisco. Together they make the Carmen, Eugenia, and María Eugenia same-person explanation strong but not yet explicit.",
  },
  {
    date: "24 Jul 2026",
    text: "Confirmed María Eugenia Rodríguez Pacheco’s 1933 death in Humacao; the act calls her Sotero’s widow and names their son Francisco as informant.",
  },
  {
    date: "24 Jul 2026",
    text: "Found Atilano Vázquez and Juana Regina Rodríguez together in 1861 and their daughter María Isidra’s 1863 baptism, which names both sets of grandparents.",
  },
  {
    date: "24 Jul 2026",
    text: "Identified María Balbina as another daughter of Atilano and Juana Regina, and a later 1879 daughter of Atilano with Juana Paula de Santiago.",
  },
  {
    date: "24 Jul 2026",
    text: "Found María Balbina’s own 1850 baptism, establishing birth on 31 May and baptism on 25 June in Yabucoa.",
  },
  {
    date: "24 Jul 2026",
    text: "Found Atilano and Juana’s 1849 marriage and Atilano and Juana Paula’s 1875 marriage, establishing Atilano’s Juncos birthplace and Juana Regina’s death before 1870.",
  },
  {
    date: "24 Jul 2026",
    text: "Found Atilano’s matching parish and civil deaths on 3 June 1898 and added daughter Francisca, who died in 1876.",
  },
  {
    date: "24 Jul 2026",
    text: "Found Juan de Dios’s 1819 Juncos baptism, corrected the index’s 1813–1814 dates, and confirmed that he was the infant recorded dead in 1820.",
  },
  {
    date: "24 Jul 2026",
    text: "Established that Máximo Vázquez was a native of Caguas and Josefa de Ribera a native of Humacao; added their 1806 daughter Juana Jacinta.",
  },
  {
    date: "24 Jul 2026",
    text: "Resolved Francisco Polanco/Solano as Francisco Solano Vázquez Rivera through his 1878 death and daughter Dolores’s 1879 baptism.",
  },
  {
    date: "24 Jul 2026",
    text: "Expanded Máximo and Josefa’s documented child cluster to eight; Tomasa remains the sole provisional child because of her age conflict.",
  },
  {
    date: "24 Jul 2026",
    text: "Added Mariana, born in 1896, as a second documented daughter of Atilano and Juana Paula de Santiago.",
  },
  {
    date: "24 Jul 2026",
    text: "Completed an image-by-image scan of the mislabeled Yabucoa baptism item through 1856; no defensible Sotero baptism appeared, and every same-name candidate image was retained.",
  },
  {
    date: "24 Jul 2026",
    text: "Captured the original 1910 Sotero–María household. Its marriage duration and seven-child count confirm the family, while Sotero’s age creates an unresolved about-1847 versus about-1860 birth conflict.",
  },
  {
    date: "24 Jul 2026",
    text: "Mapped the Yabucoa film gap: item 2 covers 1838–1842 and item 3 covers 1848–1856, so both age-based baptism windows require another register or archive copy.",
  },
  {
    date: "24 Jul 2026",
    text: "Preserved every direct download, screenshot-only record, damaged lead, and rejected candidate from this pass in the private evidence archive.",
  },
  {
    date: "24 Jul 2026",
    text: "Found Mauricio Reyes Martínez’s 1882 Humacao baptism, carrying the Reyes line back to Ramón Reyes and Inés Castro and the Martínez line to Dámaso Martínez and María Rivera.",
  },
  {
    date: "24 Jul 2026",
    text: "Found Pedro and Ana across the 1910 census page break and documented Pedro’s earlier children with Juana Villafañe; Ana reported seven children born and four living.",
  },
  {
    date: "24 Jul 2026",
    text: "Retained the 1844 Ana candidate, the 1877 Benito Isabel baptism, every full record image, and every legibility crop without forcing uncertain identities together.",
  },
];
