#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const output = path.join(root, "website/app/pr-map-shapes.ts");
const endpoint =
  "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/11/query";

const params = new URLSearchParams({
  where: "STATE='72'",
  outFields: "GEOID,NAME,BASENAME",
  returnGeometry: "true",
  outSR: "4326",
  f: "geojson",
});

const response = await fetch(`${endpoint}?${params}`);
if (!response.ok) {
  throw new Error(`Census TIGERweb request failed: ${response.status}`);
}

const collection = await response.json();
if (collection.type !== "FeatureCollection" || collection.features.length !== 78) {
  throw new Error(
    `Expected 78 Puerto Rico municipios; received ${collection.features?.length ?? 0}`,
  );
}

const view = {
  width: 800,
  height: 320,
  margin: 18,
  minLon: -67.33,
  maxLon: -65.15,
  minLat: 17.85,
  maxLat: 18.55,
};

const sq = (value) => value * value;

function segmentDistanceSquared(point, start, end) {
  let x = start[0];
  let y = start[1];
  let dx = end[0] - x;
  let dy = end[1] - y;

  if (dx !== 0 || dy !== 0) {
    const t =
      ((point[0] - x) * dx + (point[1] - y) * dy) / (dx * dx + dy * dy);
    if (t > 1) {
      x = end[0];
      y = end[1];
    } else if (t > 0) {
      x += dx * t;
      y += dy * t;
    }
  }

  dx = point[0] - x;
  dy = point[1] - y;
  return dx * dx + dy * dy;
}

function simplify(points, tolerance = 0.0014) {
  if (points.length <= 4) return points;
  const threshold = sq(tolerance);
  const keep = new Uint8Array(points.length);
  keep[0] = 1;
  keep[points.length - 1] = 1;
  const stack = [[0, points.length - 1]];

  while (stack.length) {
    const [first, last] = stack.pop();
    let index = -1;
    let maxDistance = threshold;
    for (let i = first + 1; i < last; i += 1) {
      const distance = segmentDistanceSquared(points[i], points[first], points[last]);
      if (distance > maxDistance) {
        index = i;
        maxDistance = distance;
      }
    }
    if (index !== -1) {
      keep[index] = 1;
      stack.push([first, index], [index, last]);
    }
  }

  return points.filter((_, index) => keep[index]);
}

function project([longitude, latitude]) {
  const x =
    view.margin +
    ((longitude - view.minLon) / (view.maxLon - view.minLon)) *
      (view.width - view.margin * 2);
  const y =
    view.margin +
    ((view.maxLat - latitude) / (view.maxLat - view.minLat)) *
      (view.height - view.margin * 2);
  return [Number(x.toFixed(1)), Number(y.toFixed(1))];
}

function ringPath(ring) {
  const withinMap = ring.some(
    ([lon, lat]) =>
      lon >= view.minLon &&
      lon <= view.maxLon &&
      lat >= view.minLat &&
      lat <= view.maxLat,
  );
  if (!withinMap) return "";

  const simplified = simplify(ring);
  if (simplified.length < 4) return "";
  const projected = simplified.map(project);
  return `M${projected.map(([x, y]) => `${x},${y}`).join("L")}Z`;
}

function geometryPath(geometry) {
  const polygons =
    geometry.type === "Polygon" ? [geometry.coordinates] : geometry.coordinates;
  return polygons
    .flatMap((polygon) => polygon.slice(0, 1))
    .map(ringPath)
    .filter(Boolean)
    .join("");
}

const shapes = collection.features
  .map((feature) => ({
    id: feature.properties.GEOID,
    name: feature.properties.BASENAME,
    path: geometryPath(feature.geometry),
  }))
  .filter((feature) => feature.path)
  .sort((a, b) => a.name.localeCompare(b.name));

const generated = `// Generated by tools/build-pr-map.mjs from U.S. Census Bureau TIGERweb.
// Geography: Puerto Rico municipios, ACS 2025 generalized county layer.
// Source: ${endpoint}

export const puertoRicoMapView = ${JSON.stringify(view)} as const;

export const puertoRicoMunicipioShapes = ${JSON.stringify(shapes, null, 2)} as const;
`;

await writeFile(output, generated);
console.log(`Wrote ${shapes.length} municipio shapes to ${output}`);
